const keys = [
  'JWT_SECRET_KEY',
  'JWT_EXPIRY_KEY',

  'PROVIDER_KEYFILE',
  'RSA_PRIVKEY_FILE',
  'RSA_PUBKEY_FILE',

  'PROVIDER_DLEQ_SECRET',
  'PROVIDER_BABYJUB_SECRET',
  'BUYER_BABYJUB_SECRET',
  'PROVIDER_BABYJUB_PUBLIC1',
  'PROVIDER_BABYJUB_PUBLIC2',
  'BUYER_BABYJUB_PUBLIC1',
  'BUYER_BABYJUB_PUBLIC2',
  'PROVIDER_PASSWORD',

  'ESTUARY_TOKEN',
  'AWS_S3_ACCESS_KEY_ID',
  'AWS_S3_SECRET_ACCESS_KEY',
  'AWS_S3_ENDPOINT',
  'AWS_S3_BUCKET_NAME',
  'IPFS_GATEWAY',
  'IPFS_PROJECT_ID',
  'IPFS_PROJECT_SECRET',
  'ESTUARY_ENDPOINT',
  'ENABLE_PROVENANCE',
  'ARTIFACTS_FOLDER',
  'CIRCUITS_FOLDER',
  'ENABLE_COMPUTE',
  'ARGO_HOST',
  'ARGO_NAMESPACE',
  'ARGO_AUTH_TOKEN',
  'COMPUTE_PROVIDER_KEYFILE',
  'COMPUTE_PROVIDER_PASSWORD',

  'JWT_SUBSCRIPTION_SECRET_KEY',
  'NEVERMINED_PROXY_URI',
  'SUBSCRIPTION_DEFAULT_EXPIRY_TIME',
  'NETWORK_AVERAGE_BLOCK_TIME',

  'ZERODEV_PROJECT_ID',

  'NVM_BACKEND_URL',
  'NVM_BACKEND_AUTH',
  'TRACK_BACKEND_TXS',
  'NVM_APP_URL',

  // for testing
  'SEED_WORDS',
]

const config = {}

for (let k of keys) {
  config[k] = process.env[k]
}

module.exports = {
  config,
}
